### ISSUE TITLE
Explicit formulae typo in the blog?

### ISSUE THREAD

**Issue by 3for** [mir-protocol/plonky#102]
In [Fast recursive arguments based on Plonk and Halo](https://mirprotocol.org/blog/Fast-recursive-arguments-based-on-Plonk-and-Halo), “Explicit formulae” section，are $q_{low}, q_{high}$ actually the same as $r_{low}, r_{hig}$ respectively?
![image](https://user-images.githubusercontent.com/30716372/113581281-899dad80-9659-11eb-8b2f-33a6c86b217f.png)

**Comment by dlubarov** [comment]
You're right, thanks for pointing out the mistake! I just fixed it in our repo, and will start a deploy.
