### ISSUE TITLE
Benchmarking panics when generating the recursion circuit

### ISSUE THREAD

**Issue by Nashtare** [mir-protocol/plonky#89]
Hi! I wanted to try plonky but I am unable to run the benchmarks properly. The "Generating inner proof" part takes forever to finish, and the part "generating the recursion circuit" always panics and fails with the following error (running on Ubuntu18.04 with 8GB RAM, Intel i7-9750H 2.6GHz):

> Generating inner circuit
> Finished in 156.286423678s
> 
> Generating inner witness
> Finished in 0.366971488s
> 
> Generating inner proof
> Finished in 2920.980774765s
> 
> Verifying inner proof
> Finished in 75.733380387s
> 
> Generating recursion circuit...
> thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 4', /home/workspace/plonky/src/plonk_recursion.rs:460:19

I saw you were mentioning on https://www.plonk.cafe/t/plonky-recursive-proofs-based-on-plonk-and-halo/63 that you were obtaining benchmarks of 10 sec for verifier circuit of size 2^14, how did you get those results? I saw also that the test `test_proof_trivial_recursive()` in tests/prove_and_verify_recursive.rs was flawky and hence disabled, would that be linked to it? Thanks!

**Comment by dlubarov** [comment]
Hi Robin,

Sorry about that -- our code base is rather unstable at the moment, with multiple known bugs. We're working on a partial rewrite to address the known issues and add some new features.

To get benchmark data, we could look back to an old version like 33b85e6. Those old builds aren't entirely correct -- we later noticed a couple mistakes in the verification circuit -- but the benchmarks run without errors, at least for me.

Regarding the slowness, did you run with `--release`? Our debug builds have no optimizations configured so field operations are a lot slower.

**Comment by Nashtare** [comment]
Hi Daniel,
Thanks for the answer! I was not running with `--release`, my bad (I wouldn't have expected such discrepancies in the running time). 
I'll check the older version in the meantime!
Best,
